// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghgrmlzuezhacqqrwlkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZ3JtbHp1ZXpoYWNxcXJ3bGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMTk1MTIsImV4cCI6MjA0OTU5NTUxMn0.aK4m2wYXPGPsjDpxVo8sQmXpgqZ8UU5QBcECi4eIZK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);